services:
  # Main IDE Application
  ide-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - shared_workspace:/app/workspace  # Shared workspace for all containers
      - shared_projects:/app/projects     # User project files
    environment:
      - NODE_ENV=development
      - COMPILER_SERVICE_URL=http://compiler:3002
      - TERMINAL_SERVICE_URL=http://docker-terminal:3001
      - WORKSPACE_PATH=/app/workspace
      - PROJECTS_PATH=/app/projects
    depends_on:
      - compiler
      - docker-terminal
    networks:
      - ide-network
    restart: unless-stopped

  # Docker Terminal Service
  docker-terminal:
    build:
      context: .
      dockerfile: Dockerfile.terminal
    image: ai-ide-terminal:latest
    user: "501:20"  # Host user permissions for write access
    ports:
      - "3003:3001"  # Terminal server (mapped to avoid Docker Desktop conflicts)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_workspace:/workspace      # Shared workspace access
      - shared_projects:/projects        # User project files access
      - terminal_sessions:/app/sessions  # Terminal session persistence
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOCKER_HOST=unix:///var/run/docker.sock
      - WORKSPACE_PATH=/workspace
      - PROJECTS_PATH=/projects
      - TERMINAL_CONTAINER_IMAGE=ai-ide-terminal-container:latest
    networks:
      - ide-network
    restart: unless-stopped
    privileged: true  # Required for Docker-in-Docker operations

  # Terminal Container Image Builder
  terminal-container-builder:
    build:
      context: .
      dockerfile: Dockerfile.terminal-container
    image: ai-ide-terminal-container:latest
    profiles:
      - build-only

  # Multi-language Compiler Service
  compiler:
    build:
      context: .
      dockerfile: Dockerfile.compiler
    user: "501:20"  # Host user permissions for write access
    ports:
      - "3002:3002"  # Compiler service
      - "4002:4002"  # WebSocket for interactive execution
      # - "7681:7681"  # ttyd web terminal (disabled - using standalone terminal)
    volumes:
      - ./compiler-service:/app
      - shared_workspace:/workspace      # Shared workspace access
      - shared_projects:/projects        # User project files access
      - compiler_output:/app/output      # Compilation output
      - compiler_temp:/app/temp          # Temporary compilation files
      - compiler_logs:/app/logs          # Compilation logs
      - compiler_cache:/app/cache        # Compilation cache for faster builds
    environment:
      - NODE_ENV=production
      - PORT=3002
      - WORKSPACE_PATH=/workspace
      - PROJECTS_PATH=/projects
      - OUTPUT_PATH=/app/output
      - TEMP_PATH=/app/temp
      - CACHE_PATH=/app/cache
    networks:
      - ide-network
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined  # Allows various system calls needed by compilers
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    tmpfs:
      - /tmp:size=1G,exec
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Authentication Service (GitHub OAuth + manual auth)
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: velocide-auth:latest
    environment:
      - NODE_ENV=production
      - AUTH_PORT=3010
      - FRONTEND_URL=http://localhost:5173
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=http://localhost:3010/auth/github/callback
      - SESSION_SECRET=${SESSION_SECRET:-change-me}
      - JWT_SECRET=${JWT_SECRET:-change-me}
    ports:
      - "3010:3010"
    volumes:
      - ./auth-service/database:/app/database
    networks:
      - ide-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Redis for caching (optional - for future use)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ide-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # PostgreSQL for project metadata (optional - for future use)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ide_db
      POSTGRES_USER: ide_user
      POSTGRES_PASSWORD: ide_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - ide-network
    restart: unless-stopped

  # Language Server Protocol Hub (future enhancement)
  lsp-server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./lsp-server:/app
    ports:
      - "3004:3003"
    command: sh -c "npm install && npm start"
    networks:
      - ide-network
    restart: unless-stopped
    depends_on:
      - compiler

networks:
  ide-network:
    driver: bridge

volumes:
  node_modules:
  # Shared volumes for seamless integration
  shared_workspace:     # Main workspace shared across all containers
  shared_projects:      # User project files accessible by all services
  # Container-specific volumes
  terminal_sessions:    # Terminal session persistence
  compiler_output:      # Compilation output
  compiler_temp:        # Temporary compilation files  
  compiler_logs:        # Compilation logs
  compiler_cache:       # Compilation cache for faster builds
  # Database volumes
  redis_data:
  postgres_data: